name: Flash

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.0.5
      - name: Set up Haxelib dependencies
        run: |
          haxelib install lime 7.8.0 --quiet
          haxelib install openfl 8.9.7 --quiet
          haxelib dev feathersui-validators ${{ github.workspace }}
      - name: Build Flash .swc library
        run: haxelib run openfl build flash -debug
