name: Tests

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  test-neko-legacy:
    strategy:
      matrix:
        haxe-version: [4.0.5, 4.1.5]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ matrix.haxe-version }}
      - name: Set up Haxelib dependencies
        run: |
          haxelib install lime 7.8.0 --quiet
          haxelib install openfl 8.9.7 --quiet
          haxelib install utest --quiet
          haxelib dev feathersui-validators $GITHUB_WORKSPACE
      - name: Run Tests
        working-directory: test
        run: haxelib run openfl test neko
  test-html5:
    strategy:
      matrix:
        haxe-version: [4.0.5, 4.1.5, 4.2.5, 4.3.2]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ matrix.haxe-version }}
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Set up Haxelib dependencies
        run: |
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install utest --quiet
          haxelib dev feathersui-validators $GITHUB_WORKSPACE
      - name: Set up Node.js dependencies
        working-directory: test
        run: |
          npm ci
          npx playwright install
          npx playwright install-deps
      - name: Run Tests
        working-directory: test
        run: |
          haxelib run openfl build html5 -final -Dplaywright
          node playwright-runner.js
  test-neko:
    strategy:
      matrix:
        haxe-version: [4.0.5, 4.1.5, 4.2.5, 4.3.2]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ matrix.haxe-version }}
      - name: Set up Haxelib dependencies
        run: |
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install utest --quiet
          haxelib dev feathersui-validators $GITHUB_WORKSPACE
      - name: Run Tests
        working-directory: test
        run: haxelib run openfl test neko
  test-hashlink:
    strategy:
      matrix:
        haxe-version: [4.0.5, 4.1.5, 4.2.5, 4.3.2]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ matrix.haxe-version }}
      - name: Set up Haxelib dependencies
        run: |
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install utest --quiet
          haxelib dev feathersui-validators $GITHUB_WORKSPACE
      - name: Run Tests
        working-directory: test
        run: haxelib run openfl test hl
  test-air:
    strategy:
      matrix:
        haxe-version: [4.0.5, 4.1.5, 4.2.5, 4.3.2]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: joshtynjala/setup-adobe-air-action@v2
        with:
          air-version: "33.1"
          accept-license: true
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ matrix.haxe-version }}
      - name: Set up Haxelib dependencies
        run: |
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install utest --quiet
          haxelib dev feathersui-validators ${{ github.workspace }} 
          haxelib run lime config AIR_SDK ${{ env.AIR_HOME }}
      - name: Run Tests
        working-directory: test
        run: haxelib run openfl test air
